// flow-typed signature: 9e57b3449079f3596d7ca69f631f3a93
// flow-typed version: <<STUB>>/stylex_v^0.2.3/flow_v0.133.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylex'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylex' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stylex/es' {
  declare module.exports: any;
}

declare module 'stylex/src' {
  declare module.exports: any;
}

declare module 'stylex/umd/stylex' {
  declare module.exports: any;
}

declare module 'stylex/umd/stylex.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stylex/es/index' {
  declare module.exports: $Exports<'stylex/es'>;
}
declare module 'stylex/es/index.js' {
  declare module.exports: $Exports<'stylex/es'>;
}
declare module 'stylex/index' {
  declare module.exports: $Exports<'stylex'>;
}
declare module 'stylex/index.js' {
  declare module.exports: $Exports<'stylex'>;
}
declare module 'stylex/src/index' {
  declare module.exports: $Exports<'stylex/src'>;
}
declare module 'stylex/src/index.js' {
  declare module.exports: $Exports<'stylex/src'>;
}
declare module 'stylex/umd/stylex.js' {
  declare module.exports: $Exports<'stylex/umd/stylex'>;
}
declare module 'stylex/umd/stylex.min.js' {
  declare module.exports: $Exports<'stylex/umd/stylex.min'>;
}
